### ISSUE TITLE
Ignore empty diffs

### ISSUE THREAD

**Issue by andreifilip123** [t3-oss/create-t3-app-diffs#3]
Currently, we have a lot of not-empty but empty diffs like this one:

![image](https://github.com/t3-oss/create-t3-app-diffs/assets/51714798/f09b3d86-c65c-4c0f-9c9c-d1ccb55c2962)

We need to improve the diffing algorithm somehow. This needs to be done in two places:
1. The place we generate the diffs
2. The place where we check for existing diffs

If 1 doesn't generate a diff, 2 will try to generate it next time it runs the script. So we need to ignore it in 2 as well

**Comment by juliusmarminge** [comment]
> If 1 doesn't generate a diff, 2 will try to generate it next time it runs the script. So we need to ignore it in 2 as well

Store a file like `ignoredDiffs` and use that as a lookup before starting generation?

**Comment by andreifilip123** [comment]
I started working on this but will only finish this later today
